version: "3.8"
services:
  smilecdr:
    container_name: smilecdr
    image: smilecdr:2023.05.R01
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"
      - "9201:9201"
    volumes:
      - smilecdr-volume:/home/smile/smilecdr
    env_file:
      - ./smilecdr.env
    networks: 
    - demo-network
volumes:
  smilecdr-volume:

networks:
  demo-network:
    external: true