version: "3.8"
services:
  smilecdr:
    container_name: smilecdr-2023.05.R01
    image: smilecdr:2023.05.R01
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9000:9000"
      - "9100:9100"
      - "9200:9200"
      - "9201:9201"
    volumes:
      - smilecdr-volume:/home/smile/smilecdr
    environment:
      - js.contextApi.clientId=smile-cdr
      - js.contextApi.clientSecret=kG3XHKcW80E4in3ftxaZnkXFTU89VBiu
      - js.contextApi.tokenEndpoint=http://keycloak:8080/auth/realms/poc/protocol/openid-connect/token
      - js.contextApi.scopes="openid launch context"
    networks: 
    - demo-network
volumes:
  smilecdr-volume:

networks:
  demo-network:
    external: true